INSERT INTO PRACTICAS14.CARRERA
(CODIGO_CARRERA, NOMBRE)
VALUES(01, 'Ingeniería Civil');

INSERT INTO PRACTICAS14.CARRERA
(CODIGO_CARRERA, NOMBRE)
VALUES(02, 'Ingeniería Química');

INSERT INTO PRACTICAS14.CARRERA
(CODIGO_CARRERA, NOMBRE)
VALUES(05, 'Ingeniería Industrial');

INSERT INTO PRACTICAS14.CARRERA
(CODIGO_CARRERA, NOMBRE)
VALUES(03, 'Ingeniería Mecánica');

INSERT INTO PRACTICAS14.CARRERA
(CODIGO_CARRERA, NOMBRE)
VALUES(06, 'Ingeniería Mecánica Eléctrica');

INSERT INTO PRACTICAS14.CARRERA
(CODIGO_CARRERA, NOMBRE)
VALUES(07, 'Ingeniería Mecánica Industrial');

INSERT INTO PRACTICAS14.CARRERA
(CODIGO_CARRERA, NOMBRE)
VALUES(13, 'Ingeniería Electrónica');

INSERT INTO PRACTICAS14.CARRERA
(CODIGO_CARRERA, NOMBRE)
VALUES(09, 'Ingeniería en Ciencias y Sistemas');

INSERT INTO PRACTICAS14.CARRERA
(CODIGO_CARRERA, NOMBRE)
VALUES(35, 'Ingeniería Ambiental');